---
- name: '[dependencies] Install firmware-brcm80211 and wpa-supplicant'
  package:
    name:
      - wpasupplicant
      - firmware-brcm80211
    state: present
  become: yes
  tags:
    - rpi3_network
    - rpi3_network_dependencies
...
