---
- name: '[main] == RED OUTPUT IS OK == Check /lib/udev/rules.d/75-persistent-net-generator.rules == RED OUTPUT IS OK =='
  command: >
    fgrep -q 'KERNEL!="eth*[1-9]|ath*|wlan*[1-9]|msh*|ra*|sta*|ctc*|lcs*|hsi*"' \
      /lib/udev/rules.d/75-persistent-net-generator.rules
  register: result
  ignore_errors: yes
  changed_when: false
  become: yes
  when: ansible_distribution_version < 9  # before 'raspbian stretch'
  tags:
    - network

- name: '[main] Comment old pattern in 75-persistent-net-generator.rules'
  replace:
    path: /lib/udev/rules.d/75-persistent-net-generator.rules
    regexp: '^(KERNEL!=".*$)'
    replace: '#\1'
  become: yes
  when:
    - ansible_distribution_version < 9  # before 'raspbian stretch'
    - result|failed     # first method to set condition
  notify: Restart networking service
  tags:
    - network

- name: '[main] Insert right pattern into 75-persistent-net-generator.rules'
  lineinfile:
    path: /lib/udev/rules.d/75-persistent-net-generator.rules
    insertafter: '^#KERNEL!=".*$'
    line: 'KERNEL!="eth*[1-9]|ath*|wlan*[1-9]|msh*|ra*|sta*|ctc*|lcs*|hsi*" \'
  become: yes
  when:
    - ansible_distribution_version < 9  # before 'raspbian stretch'
    - result|failed     # first method to set condition
  notify: Restart networking service
  tags:
    - network

- name: '[main] Generate /etc/network/interfaces'
  template:
    src: interfaces.j2
    dest: /etc/network/interfaces
  notify: Restart networking service
  become: yes
  tags:
    - network

- meta: flush_handlers
  tags:
    - network
...
