---
- name: "[wpa_supplicant] Include tasks from dependencies.yml"
  include_tasks: dependencies.yml

- name: "[wpa_supplicant] Ensure that passphrases have appropriate length or 0 (for unsecured networks)"
  fail:
    msg: "Passphrase must be either 8-63 characters or left undefined if network in unsecured"
  with_items: "{{ rpi3_network_wifi_APs }}"
  when:
    - item.essid|length != 0  # SSID is required (see wpa_supplicant.conf man pages)
    - ( item.passphrase|length < 8 and item.passphrase|length != 0 ) or item.passphrase|length > 63

- name: "[wpa_supplicant] Encode passphrases to 254 bit PSK"
  # VERY IMPORTANT: use ' symbols around passphrase variables.
  # Otherwise some special characters like $ will be echoed by shell as random numbers.
  shell: echo '{{ item.passphrase }}' | wpa_passphrase '{{ item.essid }}'
  register: rpi3_network_psk
  with_items: "{{ rpi3_network_wifi_APs }}"
  changed_when: false
  when:
    - item.passphrase|length != 0

- name: "[wpa_supplicant] Generate {{ rpi3_network_wpa_supplicant_conf }}"
  template:
    src: wpa_supplicant.conf.j2
    dest: "{{ rpi3_network_wpa_supplicant_conf }}"
    mode: 0644
    owner: root
    group: root
  become: yes
  notify: Restart networking service

#- name: "[wpa_supplicant] Start WPA Supplicant"
#  command: wpa_supplicant -B -D nl80211 -i {{ rpi3_network_WLAN }} -c {{ rpi3_network_wpa_supplicant_conf }}
#  become: yes

#- name: "[wpa_supplicant] Connect to {{ rpi3_network_wifi_APs[0].essid }} wifi network"
#  command: wpa_cli select_network {{ rpi3_network_wifi_APs[0].essid }}
#  become: yes
...
