---
# handlers file for rpi3_network

- name: Reload networking service and systemd daemon
  systemd:
    name: networking
    daemon_reload: yes
    enabled: yes
    state: reloaded
  become: yes
...
