---
# handlers file for rpi3_network

- name: Reload networking service and systemd daemon
  systemd:
    name: networking
    daemon_reload: yes
    enabled: yes
    state: reloaded
  listen: Restart networking service
  become: yes

- name: Restart networking service
  service:
    name: networking
    state: restarted
    enabled: yes
  listen: Restart networking service
  become: yes
...
