---
# handlers file for rpi3_network

- name: 'Reload systemd daemon'
  systemd: daemon_reload=yes
  listen: Restart networking service
  become: yes

- name: 'Restart networking service'
  service:
    name: networking
    state: restarted
    enabled: yes
  listen: Restart networking service
  become: yes
...
